### ISSUE TITLE
WISER DALI dimmer is not displayed in the Homebridge

### ISSUE THREAD

**Issue by Maro-KNX-Wiser** [hansfriedrich/homebridge-feller-wiser#10]
Hello Hans Friedirch

I have been using your "Wiser-Feller" plugin on the Homebridge since the end of the week. Everything works perfectly. Since today I have a Wiser DALI dimmer integrated in the system. It is displayed on the original Wiser app, but unfortunately not in the Homebridge. 

Thank you and greetings Marco.

**Comment by hansfriedrich** [comment]
please have a try with version [1.0.17](https://github.com/hansfriedrich/homebridge-feller-wiser/releases/tag/1.0.17)

**Comment by Maro-KNX-Wiser** [comment]
> please have a try with version [1.0.17](https://github.com/hansfriedrich/homebridge-feller-wiser/releases/tag/1.0.17)


Hallo Hansfriedirch 

Besten Dank für Dein Feedback - ich war Ferienbedingt Abwesend. 

Es funktioniert mit dem Update. 

Beste Grüsse Marco. 

Hello Hansfriedirch 

Thank you very much for your feedback - I was absent due to holidays. 

It works with the update. 

Best regards Marco.

**Comment by hansfriedrich** [comment]
Hallo Maro,
Danke für dein Feedback. Super! Freut mich, dass das Dali-Device so einfach einzubinden war. 
beste Grüsse
