### ISSUE TITLE
Roller shutter remains on "Close" after interaction

### ISSUE THREAD

**Issue by dmoibm** [hansfriedrich/homebridge-feller-wiser#12]
**Describe The Bug:**
If I operate the shutters in Apple Home, no matter in which direction, the device remains on Closed (in the detailed view) and on Close (in the device overview)

**To Reproduce:**
Open Shutter device in Home and slide up or down on the slider.

**Expected behavior:**
After reaching the desired position, the position of the roller shutter should be displayed.

**Logs:**

```
[20.9.2022, 19:09:10] [@hansfriedrich/homebridge-feller-wiser] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number -4500 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.
[20.9.2022, 19:09:10] [@hansfriedrich/homebridge-feller-wiser] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number -5800 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.
[20.9.2022, 19:09:11] [@hansfriedrich/homebridge-feller-wiser] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number -6500 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.
[20.9.2022, 19:09:12] [@hansfriedrich/homebridge-feller-wiser] This plugin generated a warning from the characteristic 'Target Position': characteristic was supplied illegal value: number -6900 exceeded minimum of 0. See https://homebridge.io/w/JtMGR for more info.
```

**Plugin Config:**

```json
{
    "bridge": {
        "name": "Homebridge AC90",
        "username": "xxx",
        "port": 51761,
        "pin": "xxx",
        "advertiser": "avahi"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "ip": "192.168.x.x",
            "authkey": "xxx",
            "platform": "feller-wiser"
        }
    ]
}
```

**Screenshots:**
no screenshot

**Environment:**

* **Plugin Version**: v1.0.17
* **Homebridge Version**: v1.5.0
* **Node.js Version**: 14.20.0
* **NPM Version**: 6.14.17
* **Operating System**: Raspbian

**Comment by hansfriedrich** [comment]
dear @dmoibm,
thank you very much for your contribution by reporting this bug. I already noticed there's something missed out.
Could you have a try with 1.0.18?

**Comment by hansfriedrich** [comment]
now please have a try with 1.0.22

**Comment by dmoibm** [comment]
dear @hansfriedrich 
Thanks for the fix! Now the shutter works perfect.
The only thing that I not understand: in homebridge I have the names as I give them in the wiser app. In Apple Home I get the kryptic device id's. (I work with same wiser user in the app and in homebridge).

**Comment by hansfriedrich** [comment]
Hi @dmoibm 
I'm glad to hear it works now. Was a bit confusing with the mapping from Hombridges ranges to the Wiser ranges of the Level. But now even the "stop" function works 🥇 
What a noticed is, the tilt-angle is conserved when you change the level. But you cannot change it within the home kit-app (till now). What comes to my mind is - I cannot differentiate between shutters (Storen) and sun-covers (Markise). With the Markise it doesn't make sense to have a tilt-angle.

To you question regarding the name. The name is setted within this line 
[in the device's logic](https://github.com/hansfriedrich/homebridge-feller-wiser/blob/2628caf849ef9ff526c1bf235c5a28a677bcde2a/src/motor.ts#L30)
I take the name from the wiser system but don't write it to the wiser system since I don't want to change any configurations on with this plugin on it.

**Comment by dmoibm** [comment]
Hello @hansfriedrich 
The problem with the range of the blind is not only the 0-10000 (Wiser) to 0-100% (Homekit). Wiser set the value to glosed, Homekit means xx% open.
I control "Senkrechtmarkisen" (Solo ZIP from Griesser) with the Wiser loads. That are more sun-covers then real shutters. And therevore I dont need the tilt-angel.

The thing with the name is: on Homebridge under Geräte it displays me the Name as I set this in the wiser app. On Apple Home it shows me the default name from the device (eg. 968d_0). 

Unfortunately, since I can't get the scene buttons via the Feller Wiser plugin, I had to get a different toolset. Actually I receive WS in node-red, sends this to MQTT over FHEM to Homebridge or direct to Homekit with a very good node-red plugin. If your are interested in this I can tell you more.
 
I think Wiser by Feller will keep us busy for a few more hours.

**Comment by hansfriedrich** [comment]
Hi Daniele,
im not sure, if you really get the names in home bridge as you set them on the wiser app - or I cannot explain it to me. As I noticed even the wiser app doesn't change any configs on the loads. 
Which names are shown when you call `GET /api/loads`?

Do the scene buttons publish messages via WS? Haven't tested that yet - but this could be awesome to integrate them as "switches"/"triggers" in home bridge - the automation behind that could be done by the apple ecosystem.

**Comment by hansfriedrich** [comment]
> Hello @hansfriedrich The problem with the range of the blind is not only the 0-10000 (Wiser) to 0-100% (Homekit). Wiser set the value to glosed, Homekit means xx% open. I control "Senkrechtmarkisen" (Solo ZIP from Griesser) with the Wiser loads. That are more sun-covers then real shutters. And therevore I dont need the tilt-angel.
> 
> The thing with the name is: on Homebridge under Geräte it displays me the Name as I set this in the wiser app. On Apple Home it shows me the default name from the device (eg. 968d_0).
> 
> Unfortunately, since I can't get the scene buttons via the Feller Wiser plugin, I had to get a different toolset. Actually I receive WS in node-red, sends this to MQTT over FHEM to Homebridge or direct to Homekit with a very good node-red plugin. If your are interested in this I can tell you more.
> 
> I think Wiser by Feller will keep us busy for a few more hours.

true 0-10000 -> 100-0. skating and inverting - I think I solved that :-D

**Comment by dmoibm** [comment]
The thing with the name on Wiser: every wiser user has its own names. You can see this on the Wiser µGateway API Documentation. Every interface that needs authorization has own properties (Rooms, Scenes, etc. and Load names).
I set the names (and Rooms, Groups, etc.) in the "Wiser Home App". To get the same names on the interfaces (eg ws uam.) I need the secret (Bearer) of the user that is logged on in the App. But you cannot get this by claim the account. Because this generates a new secret for this account and then you need to login new in the App, what generates a new secret and so one. But you can get the actual secret by logon to the µGateway and cat the account_info.json in the cli of the user that is used in the App (by mee it is the user admin). With this secret yo see the same names that was given in the "Wiser Home App". The same you can do over the µGateway.

**Comment by dmoibm** [comment]
I forgot to answer your question: it depends on the secret (authorization bearer) I use what` GET /api/loads` returns to me.

**Comment by dmoibm** [comment]
And yor second question: yes I use a smal Python Script on the µGateway attached to the scene buttens by a job that sends me the event over WS. But it sends only "click" and the ID of the button. No double click, long press and so one that could be also interesting.
