### ISSUE TITLE
Anfrage nach Email Kontakt

### ISSUE THREAD

**Issue by mgoeller** [hansfriedrich/homebridge-feller-wiser#21]
Hallo Hans Friedrich

Wir sind ein Hersteller im Bereich HomeKit / Matter aus Zürich, und würden uns gerne mit dir bzgl. deinem Feller Wiser Homebridge Plugin unterhalten. Kannst du mich bitte unter mg (at) atios.ch kontaktieren?

Danke & Gruss
Malte

**Comment by hansfriedrich** [comment]
Hallo Malte,

Vielen Dank für dein Angebot. Das klingt sehr interessant und würde das Homebridge-Plugin sicher ein Stück weit professioneller machen.
In welchem Umfang hast du dir das vorgestellt? Hast du mir euren bisherigen Quellcode (oder Auszüge davon) verfügbar?

Beste Grüsse
Hans
