### ISSUE TITLE
Issue with unique ID

### ISSUE THREAD

**Issue by thomail** [hansfriedrich/homebridge-feller-wiser#4]
Hey there,
thank you very much for your efforts on making this repo!
Is there a chance that this plugin would create unique identifiers properly? Problem for me is that homeassistant needs this to find the devices. For reference see this discussion: https://github.com/home-assistant/core/issues/50811

**Comment by hansfriedrich** [comment]
Hey thomail,
thank you for your contribution. 
As for now it wasn't necessary for me to have proper metadata for the accessories. It shouldn't that effort to set these metadata. Actually till now the accessories (loads in Wiser speech) get their uuid set by load-name, load-id and load channel. This can be published to the right characteristic.

**Comment by hansfriedrich** [comment]
published in version 1.0.16

**Comment by hansfriedrich** [comment]
Hey to thomail,
could you check this solves this issue?
Best regards

**Comment by thomail** [comment]
works like a charm! thank you very much and let me know if you need any testings to be done!
