### ISSUE TITLE
problem with setting up the plugin

### ISSUE THREAD

**Issue by Villagio88** [hansfriedrich/homebridge-feller-wiser#7]
Hi @hansfriedrich thank you very much for your plugin. I was so happy when i discovered it. Unfortunately, I'm not able to get the plugin up and running. Maybe you can help.

 This is my config:

```
{
    "bridge": {
        "name": "Homebridge 189D",
        "username": "0E:A7:E5:D6:18:9D",
        "port": 51046,
        "pin": "xxx-xx-xxx"
    },
    "accessories": [],
    "platforms": [
        {
            "name": "Config",
            "port": 8581,
            "platform": "config"
        },
        {
            "ip": "192.168.1.51",
            "platform": "feller-wiser",
            "_bridge": {
                "port": 57992
            }
        }
    ],
    "disabledPlugins": []
}
```

And this is the error i get:

```
TypeError: Cannot read properties of undefined (reading 'toUpperCase')
    at /usr/local/lib/node_modules/homebridge/src/server.ts:411:75
    at Array.forEach (<anonymous>)
    at Server.loadPlatforms (/usr/local/lib/node_modules/homebridge/src/server.ts:372:27)
    at Server.start (/usr/local/lib/node_modules/homebridge/src/server.ts:159:29)
```

Thank you very much for your help anyway!

**Comment by hansfriedrich** [comment]
@Villagio88 may I ask if you had a enlightened moment to manage the api-key creation?

**Comment by Villagio88** [comment]
Hi, yes I was able to get it up and running! Thank you very much for your help.


Andrin Villa

............................................................................................
Prätschliweg 7
CH-7000 Chur
Tel. Mobil +41 79 406 38 92
.............................................................................................
***@***.******@***.***>
www.andrinvilla.com<http://www.andrinvilla.com/>

.............................................................................................

Facebook <https://www.facebook.com/andrin.villa/> · Instagram <https://www.instagram.com/andrin_villa/> · LinkedIn<https://www.linkedin.com/in/andrin-villa-081728157>· YouTube <https://www.youtube.com/user/andrinvilla> · ***@***.***/>



________________________________
Von: hansfriedrich ***@***.***>
Gesendet: Thursday, July 14, 2022 7:36:21 PM
An: hansfriedrich/homebridge-feller-wiser ***@***.***>
Cc: Villagio88 ***@***.***>; Mention ***@***.***>
Betreff: Re: [hansfriedrich/homebridge-feller-wiser] problem with setting up the plugin (Issue #7)


@Villagio88<https://github.com/Villagio88> may I ask if you had a enlightened moment to manage the api-key creation?

**Comment by hansfriedrich** [comment]
deleted Villagio88 's reply due to personal information. 
@Villagio88, thanks for the reply. Nice to hear you managed it. I assume you don't want to have these informations here.
